spring.application.name=backend
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-2ccabc5b-loy7153-9498.e.aivencloud.com:17957/smart_factory_db?useSSL=true&serverTimezone=Asia/Seoul
spring.datasource.username=avnadmin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.backend.dto
